teste
diegomors/speedup pull request #2
Opened 2022-08-14 21:11 UTC by sabrinapansera

2022-08-20 20:37 UTC, sabrinapansera commented
Alterações figma

2022-09-04 13:52 UTC, diegomors requested changes

2022-09-04 13:52 UTC, diegomors commented on lib/shared/extensions/my_build_context_extension.dart
>    ScreenSize get screenSize => MediaQuery.of(this).size.width > 1440
@sabrinapansera acredito que no Figma o layout wide começa em 1920px de largura.
<img width="868" alt="Screen Shot 2022-09-04 at 10 45 55" src="https://user-images.githubusercontent.com/4834401/188316786-5e97a551-eb05-437c-b49a-ceb3ba1326ff.png">

2022-09-04 13:52 UTC, diegomors commented on lib/shared/extensions/my_build_context_extension.dart
> +      : MediaQuery.of(this).size.width > 428 && MediaQuery.of(this).size.width <= 1440
@sabrinapansera em reunião com o time de desenvolvimento, decidimos que iremos usar a largura maxima de 800 para dispositivos moveis. Entao, nessa linha ficaria melhor o seguinte codigo:

`MediaQuery.of(this).size.width > 800 && MediaQuery.of(this).size.width < 1920`

2022-10-23 23:38 UTC, diegomors commented
As correções já foram incorporadas no projeto, não será mais necessário este PR.

2022-10-23 23:38 UTC, closed without merging